use serde::{Deserialize, Serialize};
use diesel::{Queryable, Insertable, AsChangeset, Selectable, Associations};

use diesel::QueryableByName;

#[derive(Queryable, Selectable, Associations, Debug, PartialEq, Serialize, Deserialize, Clone, Insertable, AsChangeset, QueryableByName)]
#[diesel(belongs_to(super::bank_info::BankInfo, foreign_key = lc_issuing_bank_id))]


#[diesel(table_name = crate::repository::schema::lc_info_table)]

pub struct LcInfo {
    #[serde(default)]
    pub lc_location_code: Option<i32>,
    pub lc_id: i32,
    pub lc_preparer: Option<String>,
    pub lc_pk_preparer: Option<String>,
    pub lc_pc_prep: Option<String>,
    pub lc_pc_chker: Option<String>,
    pub lc_bill_to: Option<String>,
    pub lc_customer_id: Option<i32>,
    pub lc_status: Option<String>,
    pub lc_special_instructions: Option<String>,
    pub lc_amount: Option<f64>,
    pub lc_tolerance: Option<String>,
    pub lc_previous_lc_draws: Option<String>,
    pub lc_time_draft: Option<String>,
    pub lc_number_of_days: Option<String>,
    pub lc_country: Option<String>,
    pub lc_reference_number: Option<String>,
    pub lc_balance: Option<String>,
    pub lc_dp: Option<String>,
    pub lc_ip: Option<String>,
    pub lc_previous_lc_draws_running: Option<String>,
    pub lc_returning_balance: Option<String>,
    pub lc_currency: Option<String>,
    pub lc_fn: Option<String>,
    pub lc_charges: Option<String>,
    pub lc_add_charges: Option<String>,
    pub lc_fees_due: Option<String>,
    pub lc_cargo_ins_cost: Option<String>,
    pub lc_cargo_ins_sell_price: Option<String>,
    pub lc_rhdc_invoice_for_customer: Option<String>,
    pub lc_rhdc_invoice_for_fn_banks: Option<String>,
    pub lc_advising_bank_id: Option<i32>,
    pub lc_advising_bank_ref: Option<String>,
    pub lc_issuing_bank_id: Option<i32>,
    pub lc_issuing_bank_ref: Option<String>,
    pub lc_negotiating_bank_id: Option<i32>,
    pub lc_commission_type: Option<String>,
    pub lc_tranche_count: Option<String>,
    pub lc_acceptan: Option<String>,
    pub lc_doc_prep: Option<String>,
    pub lc_confirm: Option<String>,
    pub lc_other: Option<String>,
    pub lc_discount: Option<String>,
    pub lc_phone_forwarder_shipper: Option<String>,
    pub lc_pending_inf_tracing_status_in_pc_or_void: Option<String>,
    pub lc_net_paid: Option<String>,
    pub lc_bank_charges: Option<String>,
    pub lc_negotiating_bank_reference: Option<String>,
    pub lc_applicant_name: Option<String>,
    pub lc_third_party_shipper_name: Option<String>,
    pub lc_applicant_address: Option<String>,
    pub lc_third_party_shipper_address: Option<String>,
    pub lc_applicant_fax: Option<String>,
    pub lc_drawee: Option<String>,
    pub lc_load_on_board: Option<String>,
    pub lc_for_transport_to: Option<String>,
    pub lc_tenor_of_draft: Option<String>,
    pub lc_drawn_under_statement_of_draft: Option<String>,
    pub lc_large_merchandise_description_invoice: Option<String>,
    pub lc_sales_terms: Option<String>,
    pub lc_location_of_sales_terms: Option<String>,
    pub lc_consign_to_party: Option<String>,
    pub lc_freight: Option<String>,
    pub lc_notify_party: Option<String>,
    pub lc_short_merchandise_description_for_bl: Option<String>,
    pub lc_short_merchandise_description_for_co: Option<String>,
    pub lc_global_field: Option<String>,
    pub lc_limited_certifications: Option<String>,
    pub lc_awd_or_bl_merchandise_description: Option<String>,
    pub lc_insurance_merchandise_description: Option<String>,
    pub lc_shipping_advice_merchandise_description: Option<String>,
    pub lc_value_for_carriage: Option<String>,
    pub lc_value_for_customers: Option<String>,
    pub lc_gross_weight: Option<String>,
    pub lc_measurements: Option<String>,
    pub lc_net_weight: Option<String>,
    pub lc_chargeable_weight: Option<String>,
    pub lc_weight_in_lbs: Option<String>,
    pub lc_other_charges_due_agent: Option<String>,
    pub lc_tl_forwarder_name: Option<String>,
    pub lc_forwarder_address: Option<String>,
    pub lc_partial_or_comp_shipment: Option<String>,
    pub lc_carrier_name: Option<String>,
    pub lc_vessel_name: Option<String>,
    pub lc_place_of_delivery_by: Option<String>,
    pub lc_for_transhipment_to: Option<String>,
    pub lc_type_of_move: Option<String>,
    pub lc_place_of_receipt_by: Option<String>,
    pub lc_other_chgs_due_carrier: Option<String>,
    pub lc_freight_charge: Option<String>,
    pub lc_insurance_chg: Option<String>,
    pub lc_insurance_percentage: Option<String>,
    pub lc_insurance_amt: Option<String>,
    pub lc_invoice_num: Option<i32>,
    pub lc_mawb_no: Option<String>,
    pub lc_mobl_no: Option<String>,
    pub lc_hawb_hobl_no: Option<String>,
    pub lc_marks_and_numbers: Option<String>,
    pub lc_no_of_pieces: Option<String>,
    pub lc_dimensions: Option<String>,
    pub lc_po_no: Option<String>,
    pub lc_city_state_of_origin: Option<String>,
    pub lc_country_of_origin: Option<String>,
    pub lc_1st_flight_number: Option<String>,
    pub lc_2nd_flight_number: Option<String>,
    pub lc_1st_to_city_code: Option<String>,
    pub lc_1st_to_city_code_value: Option<String>,
    pub lc_insurance_company_name: Option<String>,
    pub lc_insurance_company_address: Option<String>,
    pub lc_insurance_company_fax: Option<String>,
    pub lc_other_receipt_name: Option<String>,
    pub lc_other_receipt_address: Option<String>,
    pub lc_other_receipt_fax: Option<String>,
    pub lc_other_courier_name: Option<String>,
    pub lc_other_courier_add: Option<String>,
    pub lc_type: Option<String>,
    pub lc_amount_of_draw: Option<String>,
    pub lc_master_id: Option<i32>,
    pub lc_secondapplicant_header: Option<String>,
    pub lc_secondapplicant_name: Option<String>,
    pub lc_secondapplicant_address: Option<String>,
    pub lc_date_id: Option<i32>,
    pub lc_courier_id: Option<i32>,
    pub lc_information_currency: Option<String>,


}
