-- Create a table to store the IATA code mappings
CREATE TABLE IF NOT EXISTS iata_codes (
    iata_id SERIAL PRIMARY KEY,
    mawb_code text,
    iata_code text,
    airline_name text
);

-- Insert the provided data into the table
INSERT INTO iata_codes (mawb_code, iata_code, airline_name)
VALUES
('001', 'AA', 'American Airlines'),
('002', '2G', 'CargoItalia (alternate)'),
('005', 'CO', 'Continental Airlines'),
('006', 'DL', 'Delta Air Lines'),
('012', 'NW', 'Northwest Airlines (alternate site)'),
('014', 'AC', 'Air Canada'),
('016', 'UA', 'United Airlines Cargo'),
('018', 'CP', 'Canadian Airlines Int´l'),
('020', 'LH', 'Lufthansa Cargo AG'),
('023', 'FX', 'Fedex'),
('027', 'AS', 'Alaska Airlines'),
('037', 'US', 'USAirways'),
('042', 'RG', 'VARIG Brazilian Airlines'),
('043', 'KA', 'Dragonair'),
('045', 'LA', 'LAN Chile'),
('047', 'TP', 'TAP Air Portugal'),
('048', 'CY', 'Cyprus Airways'),
('050', 'OA', 'Olympic Airways'),
('053', 'EI', 'Aer Lingus Cargo'),
('055', 'AZ', 'Alitalia'),
('057', 'AF', 'Air France'),
('058', 'IC', 'Indian Airlines'),
('061', 'HM', 'Air Seychelles'),
('064', 'OK', 'Czech Airlines'),
('065', 'SV', 'Saudi Arabian Airlines'),
('070', 'RB', 'Syrian Arab Airlines'),
('071', 'ET', 'Ethiopian Airlines'),
('072', 'GF', 'Gulf Air'),
('074', 'KL', 'KLM Cargo'),
('075', 'IB', 'Iberia'),
('076', 'ME', 'Middle East Airlines'),
('077', 'MS', 'Egyptair'),
('079', 'PR', 'Philippine Airlines'),
('080', 'LO', 'LOT Polish Airlines'),
('081', 'QF', 'Qantas Airways'),
('082', 'SN', 'Brussels Airlines'),
('083', 'SA', 'South African Airways'),
('086', 'NZ', 'Air New Zealand'),
('090', 'IT', 'Kingfisher Airlines'),
('093', 'KD', 'KD Avia'),
('096', 'IR', 'Iran Air'),
('098', 'AI', 'Air India'),
('105', 'AY', 'Finnair'),
('106', 'BW', 'Caribbean Airlines'),
('108', 'FI', 'Icelandair'),
('112', 'CK', 'China Cargo Airlines'),
('114', 'LY', 'EL AL'),
('115', 'JU', 'JAT Airways'),
('117', 'SK', 'SAS-Scandinavian Airlines System'),
('118', 'DT', 'TAAG Angola Airlines'),
('119', 'LM', 'Air ALM'),
('124', 'AH', 'Air Algerie'),
('125', 'BA', 'British Airways'),
('126', 'GA', 'Garuda Indonesia'),
('129', 'MP', 'Martinair Cargo'),
('131', 'JL', 'Japan Airlines'),
('133', 'LR', 'LACSA Airlines of Costa Rica'),
('139', 'AM', 'Aeromexico Cargo'),
('140', 'LI', 'LIAT Airlines'),
('147', 'AT', 'Royal Air Maroc'),
('148', 'LN', 'Libyan Airlines'),
('157', 'QR', 'Qatar Airways'),
('160', 'CX', 'Cathay Pacific Airways'),
('163', '3V', 'TNT Airways'),
('165', 'JP', 'Adria Airways'),
('172', 'CV', 'Cargolux Airlines'),
('176', 'EK', 'Emirates'),
('180', 'KE', 'Korean Air'),
('182', 'MA', 'Malev Hungarian Airlines'),
('183', 'RG', 'VARIG Brazilian Airlines'),
('189', 'JI', 'Jade Cargo International'),
('201', 'JM', 'Air Jamaica'),
('202', 'TA', 'TACA'),
('205', 'NH', 'ANA All Nippon Cargo'),
('214', 'PK', 'Pakistan Int´l Airlines'),
('217', 'TG', 'Thai Airways'),
('229', 'KU', 'Kuwait Airways'),
('230', 'CM', 'Copa Airlines Cargo'),
('231', 'NG', 'Lauda Air'),
('232', 'MH', 'Malaysian Airline System'),
('234', 'JD', 'Japan Air System'),
('235', 'TK', 'Turkish Airlines'),
('236', 'BD', 'British Midland Airways'),
('239', 'MK', 'Air Mauritius'),
('257', 'OS', 'Austrian Cargo'),
('258', 'MD', 'Air Madagascar'),
('265', 'EF', 'Far Eastern Air Transport'),
('266', 'LT', 'LTU (Leisure Cargo)'),
('270', 'TL', 'Trans Mediterranean Airways'),
('272', 'K4', 'Kalitta Air'),
('288', 'LD', 'Air Hong Kong'),
('297', 'CI', 'China Airlines'),
('301', '5S', 'Global Aviation and Services'),
('302', 'OO', 'Sky West Airlines'),
('307', 'WE', 'Centurion Air Cargo'),
('324', 'SC', 'Shandong Airlines (Chinese)'),
('330', 'RF', 'Florida West International Airways'),
('345', 'NC', 'Northern Air Cargo'),
('356', 'C8', 'Cargolux Italia'),
('369', '5Y', 'Atlas Air'),
('378', 'KX', 'Cayman Airways'),
('390', 'A3', 'Aegean Airlines'),
('403', 'PO', 'Polar Air Cargo'),
('404', 'JW', 'Arrow Air'),
('406', '5X', 'UPS Air Cargo'),
('416', 'N8', 'National Air Cargo'),
('421', 'S7', 'Siberia Airlines'),
('423', 'ER', 'DHL Aviation/DHL Airways'),
('465', 'KC', 'Air Astana'),
('479', 'ZH', 'Shenzhen Airlines (Chinese)'),
('507', 'SU', 'Aeroflot'),
('512', 'RJ', 'Royal Jordanian'),
('526', 'WN', 'Southwest Airlines'),
('529', 'A2', 'Cielos Airlines'),
('549', 'M3', 'ABSA Aerolinhas Brasileiras'),
('552', 'M2', 'Mario’s Air'),
('564', 'XQ', 'Sun Express'),
('566', 'PS', 'Ukraine Int´l Airlines'),
('572', '9U', 'Air Moldova'),
('575', '7C', 'Coyne Airways'),
('580', 'RU', 'AirBridge Cargo'),
('589', '9W', 'Jet Airways'),
('603', 'UL', 'SriLankan Cargo'),
('604', 'UY', 'Cameroon Airlines'),
('607', 'EY', 'ETIHAD Airways'),
('615', 'QY', 'DHL Aviation / European Air Transport'),
('618', 'SQ', 'Singapore Airlines'),
('623', 'FB', 'Bulgaria Air'),
('631', 'GL', 'Air Greenland'),
('635', 'IY', 'Yemenia Yemen Airways'),
('643', 'KM', 'Air Malta'),
('656', 'PX', 'Air Niugini'),
('657', 'BT', 'Air Baltic'),
('672', 'BI', 'Royal Brunei Airlines'),
('675', 'NX', 'Air Macau'),
('695', 'BR', 'Eva Airways'),
('700', '5C', 'CAL Cargo Air Lines'),
('706', 'KQ', 'Kenya Airways'),
('716', 'MB', 'MNG Airlines'),
('724', 'LX', 'Swiss'),
('729', 'QT', 'Tampa Airlines'),
('731', 'MF', 'Xiamen Airlines'),
('737', 'SP', 'SATA Air Acores'),
('738', 'VN', 'Vietnam Airlines'),
('757', 'SM', 'Avient'),
('771', 'J2', 'Azerbaijan Airlines'),
('774', 'FM', 'Shanghai Airlines'),
('781', 'MU', 'China Eastern Airlines'),
('784', 'CZ', 'China Southern Airlines'),
('800', 'GD', 'Grandstar Cargo'),
('803', 'AE', 'Mandarin Airlines'),
('810', 'M6', 'Amerijet International'),
('817', 'S6', 'SAC South American Airways'),
('825', 'F4', 'Shanghai Airlines Cargo'),
('831', 'OU', 'Croatia Airlines'),
('851', 'N8', 'Hong Kong Airlines'),
('858', 'FK', 'Africa West'),
('862', 'EV', 'Atlantic Southeast Airlines'),
('865', 'MY', 'MASAir'),
('870', 'VV', 'Aerosvit'),
('871', 'Y8', 'Yangtze River Express Airlines'),
('873', '6R', 'AeroUnion'),
('876', '3U', 'Sichuan Airlines'),
('880', 'HU', 'Hainan Airlines (Chinese)'),
('881', 'DE', 'Condor Flugdienst'),
('886', 'OH', 'Comair'),
('901', 'B1', 'TAB Cargo'),
('907', 'QN', 'Air Armenia'),
('928', 'UZ', 'Buraq Air Transport (Arabic only)'),
('932', 'VS', 'Virgin Atlantic'),
('933', 'KZ', 'Nippon Cargo Airlines'),
('957', 'JJ', 'TAM Brazilian Airlines'),
('958', '7I', 'Insel Air Cargo'),
('960', 'OV', 'Estonian Air'),
('976', 'QO', 'Aeromexpress Cargo'),
('988', 'OZ', 'Asiana Airlines'),
('989', 'IJ', 'Great Wall Airlines'),
('996', 'UX', 'Air Europa Cargo'),
('997', 'BG', 'Biman Bangladesh'),
('999', 'CA', 'Air China');






