-- Admin Table
DROP TABLE IF EXISTS ADMIN_TABLE;

-- Customer BANK AND LC Table
DROP TABLE IF EXISTS CUSTOMER_INFO_TABLE;
DROP TABLE IF EXISTS BANK_INFO_TABLE;
DROP TABLE IF EXISTS COURIER_INFO_TABLE;
DROP TABLE IF EXISTS DATE_INFO_TABLE;
DROP TABLE IF EXISTS LC_INFO_TABLE;

-- Currency Table
DROP TABLE IF EXISTS CURRENCY_TABLE;


-- CSC Table
DROP TABLE IF EXISTS CSC_CITY_TABLE;
DROP TABLE IF EXISTS CSC_STATES_TABLE;
DROP TABLE IF EXISTS CSC_COUNTRIES_TABLE;



