-- SELECT_TENOR_OF_DRAFT Table
CREATE TABLE
  SELECT_TABLE (
    SELECT_TABLE_ID SERIAL PRIMARY KEY,
    FIELD_NAME TEXT,
    FIELD_VALUE TEXT
  );

INSERT INTO
  SELECT_TABLE (field_name, field_value)
VALUES
  ('TENOR OF DRAFT', 'SIGHT'),
  ('TENOR OF DRAFT', '30 DAYS AFTER BL DATE'),
  ('TENOR OF DRAFT', '60 DAYS AFTER BL DATE'),
  ('TENOR OF DRAFT', '90 DAYS AFTER BL DATE'),
  ('TENOR OF DRAFT', '150 DAYS AFTER BL DATE'),
  ('TENOR OF DRAFT', '180 DAYS AFTER BL DATE'),
  ('TENOR OF DRAFT', '30 DAYS AFTER AWB DATE'),
  ('TENOR OF DRAFT', '60 DAYS AFTER AWB DATE'),
  ('TENOR OF DRAFT', '90 DAYS AFTER AWB DATE'),
  ('TENOR OF DRAFT', '120 DAYS AFTER AWB DATE'),
  ('TENOR OF DRAFT', '150 DAYS AFTER AWB DATE'),
  ('TENOR OF DRAFT', '180 DAYS AFTER AWB DATE'),
  ('TENOR OF DRAFT', '30 DAYS AFTER SIGHT'),
  ('TENOR OF DRAFT', '60 DAYS AFTER SIGHT'),
  ('TENOR OF DRAFT', '90 DAYS AFTER SIGHT'),
  ('TENOR OF DRAFT', '120 DAYS AFTER SIGHT'),
  ('TENOR OF DRAFT', '150 DAYS AFTER SIGHT'),

  ('SALES TERMS', 'TERMS OF PRICE EXW'),
  ('SALES TERMS', 'FOB'),
  ('SALES TERMS', 'EX-WORKS'),
  ('SALES TERMS', 'CFR'),
  ('SALES TERMS', 'FCA'),
  ('SALES TERMS', 'CIF'),
  ('SALES TERMS', 'EXFACTORY'),
  ('SALES TERMS', 'C&F'),
  ('SALES TERMS', 'DDP'),
  ('SALES TERMS', 'CIP'),
  ('SALES TERMS', 'C.I.F.'),
  ('SALES TERMS', 'C AND I'),
  ('SALES TERMS', 'FAS'),
  ('SALES TERMS', 'C&I'),
  ('SALES TERMS', 'CNF'),
  ('SALES TERMS', 'CPT'),
  ('SALES TERMS', 'EX WORKS'),
  ('SALES TERMS', 'EX-FACTORY'),
  ('SALES TERMS', 'EXW'),
  ('SALES TERMS', 'EXWORKS'),
  ('SALES TERMS', 'C AND F'),

  ('MEASUREMENTS', 'K'),
  ('MEASUREMENTS', 'LBS'),
  ('MEASUREMENTS', 'KG'),
  ('MEASUREMENTS', 'KGS'),


  ('FREIGHT', 'TO PAY'),
  ('FREIGHT', 'TO BE PAID'),
  ('FREIGHT', 'PREPAID'),
  ('FREIGHT', 'TO BE PREPAID'),
  ('FREIGHT', 'PAID'),
  ('FREIGHT', 'COLLECT'),
  ('FREIGHT', 'PAYABLE AT DESTINATION'),
  ('FREIGHT', 'TO COLLECT');