ALTER TABLE LC_INFO_TABLE
ADD CONSTRAINT fk_lc_issuing_bank
FOREIGN KEY (LC_ISSUING_BANK_ID)
REFERENCES BANK_INFO_TABLE(BANK_ID);

ALTER TABLE LC_INFO_TABLE
ADD CONSTRAINT fk_lc_customer
FOREIGN KEY (LC_CUSTOMER_ID)
REFERENCES CUSTOMER_INFO_TABLE(CUSTOMER_ID);

ALTER TABLE LC_INFO_TABLE
ADD CONSTRAINT fk_lc_date
FOREIGN KEY (LC_DATE_ID)
REFERENCES DATE_INFO_TABLE(DATE_ID);

ALTER TABLE LC_INFO_TABLE
ADD CONSTRAINT fk_lc_courier
FOREIGN KEY (LC_COURIER_ID)
REFERENCES COURIER_INFO_TABLE(COURIER_ID);


-- CSC
ALTER TABLE CSC_STATES_TABLE
ADD CONSTRAINT fk_states_countries
FOREIGN KEY (country_id)
REFERENCES CSC_COUNTRIES_TABLE(id);


ALTER TABLE CSC_CITY_TABLE
ADD CONSTRAINT fk_city_countries
FOREIGN KEY (country_id)
REFERENCES CSC_COUNTRIES_TABLE(id);


ALTER TABLE CSC_CITY_TABLE
ADD CONSTRAINT fk_city_states
FOREIGN KEY (state_id)
REFERENCES CSC_STATES_TABLE(id);