ALTER TABLE LC_INFO_TABLE ADD COLUMN tsvector_lc_column tsvector;


UPDATE LC_INFO_TABLE SET tsvector_lc_column = to_tsvector('english',
    coalesce(lc_location_code::text, '') || ' ' ||
    coalesce(lc_id::text, '') || ' ' ||
    coalesce(lc_preparer, '') || ' ' ||
    coalesce(lc_pk_preparer, '') || ' ' ||
    coalesce(lc_pc_prep, '') || ' ' ||
    coalesce(lc_pc_chker, '') || ' ' ||
    coalesce(lc_bill_to, '') || ' ' ||
    coalesce(lc_customer_id::text, '') || ' ' ||
    coalesce(lc_status, '') || ' ' ||
    coalesce(lc_special_instructions, '') || ' ' ||
    coalesce(lc_amount::text, '') || ' ' ||
    coalesce(lc_tolerance, '') || ' ' ||
    coalesce(lc_previous_lc_draws, '') || ' ' ||
    coalesce(lc_time_draft, '') || ' ' ||
    coalesce(lc_number_of_days, '') || ' ' ||
    coalesce(lc_country, '') || ' ' ||
    coalesce(lc_reference_number, '') || ' ' ||
    coalesce(lc_balance, '') || ' ' ||
    coalesce(lc_dp, '') || ' ' ||
    coalesce(lc_ip, '') || ' ' ||
    coalesce(lc_previous_lc_draws_running, '') || ' ' ||
    coalesce(lc_returning_balance, '') || ' ' ||
    coalesce(lc_currency, '') || ' ' ||
    coalesce(lc_fn, '') || ' ' ||
    coalesce(lc_charges, '') || ' ' ||
    coalesce(lc_add_charges, '') || ' ' ||
    coalesce(lc_fees_due, '') || ' ' ||
    coalesce(lc_cargo_ins_cost, '') || ' ' ||
    coalesce(lc_cargo_ins_sell_price, '') || ' ' ||
    coalesce(lc_rhdc_invoice_for_customer, '') || ' ' ||
    coalesce(lc_rhdc_invoice_for_fn_banks, '') || ' ' ||
    coalesce(lc_advising_bank_id::text, '') || ' ' ||
    coalesce(lc_advising_bank_ref, '') || ' ' ||
    coalesce(lc_issuing_bank_id::text, '') || ' ' ||
    coalesce(lc_issuing_bank_ref, '') || ' ' ||
    coalesce(lc_negotiating_bank_id::text, '') || ' ' ||
    coalesce(lc_commission_type, '') || ' ' ||
    coalesce(lc_tranche_count, '') || ' ' ||
    coalesce(lc_acceptan, '') || ' ' ||
    coalesce(lc_doc_prep, '') || ' ' ||
    coalesce(lc_confirm, '') || ' ' ||
    coalesce(lc_other, '') || ' ' ||
    coalesce(lc_discount, '') || ' ' ||
    coalesce(lc_phone_forwarder_shipper, '') || ' ' ||
    coalesce(lc_pending_inf_tracing_status_in_pc_or_void, '') || ' ' ||
    coalesce(lc_net_paid, '') || ' ' ||
    coalesce(lc_bank_charges, '') || ' ' ||
    coalesce(lc_negotiating_bank_reference, '') || ' ' ||
    coalesce(lc_applicant_name, '') || ' ' ||
    coalesce(lc_third_party_shipper_name, '') || ' ' ||
    coalesce(lc_applicant_address, '') || ' ' ||
    coalesce(lc_third_party_shipper_address, '') || ' ' ||
    coalesce(lc_applicant_fax, '') || ' ' ||
    coalesce(lc_drawee, '') || ' ' ||
    coalesce(lc_load_on_board, '') || ' ' ||
    coalesce(lc_for_transport_to, '') || ' ' ||
    coalesce(lc_tenor_of_draft, '') || ' ' ||
    coalesce(lc_drawn_under_statement_of_draft, '') || ' ' ||
    coalesce(lc_large_merchandise_description_invoice, '') || ' ' ||
    coalesce(lc_sales_terms, '') || ' ' ||
    coalesce(lc_location_of_sales_terms, '') || ' ' ||
    coalesce(lc_consign_to_party, '') || ' ' ||
    coalesce(lc_freight, '') || ' ' ||
    coalesce(lc_notify_party, '') || ' ' ||
    coalesce(lc_short_merchandise_description_for_bl, '') || ' ' ||
    coalesce(lc_short_merchandise_description_for_co, '') || ' ' ||
    coalesce(lc_global_field, '') || ' ' ||
    coalesce(lc_limited_certifications, '') || ' ' ||
    coalesce(lc_awd_or_bl_merchandise_description, '') || ' ' ||
    coalesce(lc_insurance_merchandise_description, '') || ' ' ||
    coalesce(lc_shipping_advice_merchandise_description, '') || ' ' ||
    coalesce(lc_value_for_carriage, '') || ' ' ||
    coalesce(lc_value_for_customers, '') || ' ' ||
    coalesce(lc_gross_weight, '') || ' ' ||
    coalesce(lc_measurements, '') || ' ' ||
    coalesce(lc_net_weight, '') || ' ' ||
    coalesce(lc_chargeable_weight, '') || ' ' ||
    coalesce(lc_weight_in_lbs, '') || ' ' ||
    coalesce(lc_other_charges_due_agent, '') || ' ' ||
    coalesce(lc_tl_forwarder_name, '') || ' ' ||
    coalesce(lc_forwarder_address, '') || ' ' ||
    coalesce(lc_partial_or_comp_shipment, '') || ' ' ||
    coalesce(lc_carrier_name, '') || ' ' ||
    coalesce(lc_vessel_name, '') || ' ' ||
    coalesce(lc_place_of_delivery_by, '') || ' ' ||
    coalesce(lc_for_transhipment_to, '') || ' ' ||
    coalesce(lc_type_of_move, '') || ' ' ||
    coalesce(lc_place_of_receipt_by, '') || ' ' ||
    coalesce(lc_other_chgs_due_carrier, '') || ' ' ||
    coalesce(lc_freight_charge, '') || ' ' ||
    coalesce(lc_insurance_chg, '') || ' ' ||
    coalesce(lc_insurance_percentage, '') || ' ' ||
    coalesce(lc_insurance_amt, '') || ' ' ||
    coalesce(lc_invoice_num::text, '') || ' ' ||
    coalesce(lc_mawb_no, '') || ' ' ||
    coalesce(lc_mobl_no, '') || ' ' ||
    coalesce(lc_hawb_hobl_no, '') || ' ' ||
    coalesce(lc_marks_and_numbers, '') || ' ' ||
    coalesce(lc_no_of_pieces, '') || ' ' ||
    coalesce(lc_dimensions, '') || ' ' ||
    coalesce(lc_po_no, '') || ' ' ||
    coalesce(lc_city_state_of_origin, '') || ' ' ||
    coalesce(lc_country_of_origin, '') || ' ' ||
    coalesce(lc_1st_flight_number, '') || ' ' ||
    coalesce(lc_2nd_flight_number, '') || ' ' ||
    coalesce(lc_1st_to_city_code, '') || ' ' ||
    coalesce(lc_1st_to_city_code_value, '') || ' ' ||
    coalesce(lc_insurance_company_name, '') || ' ' ||
    coalesce(lc_insurance_company_address, '') || ' ' ||
    coalesce(lc_insurance_company_fax, '') || ' ' ||
    coalesce(lc_other_receipt_name, '') || ' ' ||
    coalesce(lc_other_receipt_address, '') || ' ' ||
    coalesce(lc_other_receipt_fax, '') || ' ' ||
    coalesce(lc_other_courier_name, '') || ' ' ||
    coalesce(lc_other_courier_add, '') || ' ' ||
    coalesce(lc_type, '') || ' ' ||
    coalesce(lc_amount_of_draw, '') || ' ' ||
    coalesce(lc_master_id::text, '') || ' ' ||
    coalesce(lc_secondapplicant_header, '') || ' ' ||
    coalesce(lc_secondapplicant_name, '') || ' ' ||
    coalesce(lc_secondapplicant_address::text, '')
);                           


CREATE INDEX index_on_lc_tsvector ON LC_INFO_TABLE USING GIN (tsvector_lc_column);


CREATE OR REPLACE FUNCTION lc_tsvector_update_function() RETURNS trigger AS $$
begin
    new.tsvector_lc_column := to_tsvector('english', 
    coalesce(NEW.lc_location_code::text, '') || ' ' ||
    coalesce(NEW.lc_id::text, '') || ' ' ||
    coalesce(NEW.lc_preparer, '') || ' ' ||
    coalesce(NEW.lc_pk_preparer, '') || ' ' ||
    coalesce(NEW.lc_pc_prep, '') || ' ' ||
    coalesce(NEW.lc_pc_chker, '') || ' ' ||
    coalesce(NEW.lc_bill_to, '') || ' ' ||
    coalesce(NEW.lc_customer_id::text, '') || ' ' ||
    coalesce(NEW.lc_status, '') || ' ' ||
    coalesce(NEW.lc_special_instructions, '') || ' ' ||
    coalesce(NEW.lc_amount::text, '') || ' ' ||
    coalesce(NEW.lc_tolerance, '') || ' ' ||
    coalesce(NEW.lc_previous_lc_draws, '') || ' ' ||
    coalesce(NEW.lc_time_draft, '') || ' ' ||
    coalesce(NEW.lc_number_of_days, '') || ' ' ||
    coalesce(NEW.lc_country, '') || ' ' ||
    coalesce(NEW.lc_reference_number, '') || ' ' ||
    coalesce(NEW.lc_balance, '') || ' ' ||
    coalesce(NEW.lc_dp, '') || ' ' ||
    coalesce(NEW.lc_ip, '') || ' ' ||
    coalesce(NEW.lc_previous_lc_draws_running, '') || ' ' ||
    coalesce(NEW.lc_returning_balance, '') || ' ' ||
    coalesce(NEW.lc_currency, '') || ' ' ||
    coalesce(NEW.lc_fn, '') || ' ' ||
    coalesce(NEW.lc_charges, '') || ' ' ||
    coalesce(NEW.lc_add_charges, '') || ' ' ||
    coalesce(NEW.lc_fees_due, '') || ' ' ||
    coalesce(NEW.lc_cargo_ins_cost, '') || ' ' ||
    coalesce(NEW.lc_cargo_ins_sell_price, '') || ' ' ||
    coalesce(NEW.lc_rhdc_invoice_for_customer, '') || ' ' ||
    coalesce(NEW.lc_rhdc_invoice_for_fn_banks, '') || ' ' ||
    coalesce(NEW.lc_advising_bank_id::text, '') || ' ' ||
    coalesce(NEW.lc_advising_bank_ref, '') || ' ' ||
    coalesce(NEW.lc_issuing_bank_id::text, '') || ' ' ||
    coalesce(NEW.lc_issuing_bank_ref, '') || ' ' ||
    coalesce(NEW.lc_negotiating_bank_id::text, '') || ' ' ||
    coalesce(NEW.lc_commission_type, '') || ' ' ||
    coalesce(NEW.lc_tranche_count, '') || ' ' ||
    coalesce(NEW.lc_acceptan, '') || ' ' ||
    coalesce(NEW.lc_doc_prep, '') || ' ' ||
    coalesce(NEW.lc_confirm, '') || ' ' ||
    coalesce(NEW.lc_other, '') || ' ' ||
    coalesce(NEW.lc_discount, '') || ' ' ||
    coalesce(NEW.lc_phone_forwarder_shipper, '') || ' ' ||
    coalesce(NEW.lc_pending_inf_tracing_status_in_pc_or_void, '') || ' ' ||
    coalesce(NEW.lc_net_paid, '') || ' ' ||
    coalesce(NEW.lc_bank_charges, '') || ' ' ||
    coalesce(NEW.lc_negotiating_bank_reference, '') || ' ' ||
    coalesce(NEW.lc_applicant_name, '') || ' ' ||
    coalesce(NEW.lc_third_party_shipper_name, '') || ' ' ||
    coalesce(NEW.lc_applicant_address, '') || ' ' ||
    coalesce(NEW.lc_third_party_shipper_address, '') || ' ' ||
    coalesce(NEW.lc_applicant_fax, '') || ' ' ||
    coalesce(NEW.lc_drawee, '') || ' ' ||
    coalesce(NEW.lc_load_on_board, '') || ' ' ||
    coalesce(NEW.lc_for_transport_to, '') || ' ' ||
    coalesce(NEW.lc_tenor_of_draft, '') || ' ' ||
    coalesce(NEW.lc_drawn_under_statement_of_draft, '') || ' ' ||
    coalesce(NEW.lc_large_merchandise_description_invoice, '') || ' ' ||
    coalesce(NEW.lc_sales_terms, '') || ' ' ||
    coalesce(NEW.lc_location_of_sales_terms, '') || ' ' ||
    coalesce(NEW.lc_consign_to_party, '') || ' ' ||
    coalesce(NEW.lc_freight, '') || ' ' ||
    coalesce(NEW.lc_notify_party, '') || ' ' ||
    coalesce(NEW.lc_short_merchandise_description_for_bl, '') || ' ' ||
    coalesce(NEW.lc_short_merchandise_description_for_co, '') || ' ' ||
    coalesce(NEW.lc_global_field, '') || ' ' ||
    coalesce(NEW.lc_limited_certifications, '') || ' ' ||
    coalesce(NEW.lc_awd_or_bl_merchandise_description, '') || ' ' ||
    coalesce(NEW.lc_insurance_merchandise_description, '') || ' ' ||
    coalesce(NEW.lc_shipping_advice_merchandise_description, '') || ' ' ||
    coalesce(NEW.lc_value_for_carriage, '') || ' ' ||
    coalesce(NEW.lc_value_for_customers, '') || ' ' ||
    coalesce(NEW.lc_gross_weight, '') || ' ' ||
    coalesce(NEW.lc_measurements, '') || ' ' ||
    coalesce(NEW.lc_net_weight, '') || ' ' ||
    coalesce(NEW.lc_chargeable_weight, '') || ' ' ||
    coalesce(NEW.lc_weight_in_lbs, '') || ' ' ||
    coalesce(NEW.lc_other_charges_due_agent, '') || ' ' ||
    coalesce(NEW.lc_tl_forwarder_name, '') || ' ' ||
    coalesce(NEW.lc_forwarder_address, '') || ' ' ||
    coalesce(NEW.lc_partial_or_comp_shipment, '') || ' ' ||
    coalesce(NEW.lc_carrier_name, '') || ' ' ||
    coalesce(NEW.lc_vessel_name, '') || ' ' ||
    coalesce(NEW.lc_place_of_delivery_by, '') || ' ' ||
    coalesce(NEW.lc_for_transhipment_to, '') || ' ' ||
    coalesce(NEW.lc_type_of_move, '') || ' ' ||
    coalesce(NEW.lc_place_of_receipt_by, '') || ' ' ||
    coalesce(NEW.lc_other_chgs_due_carrier, '') || ' ' ||
    coalesce(NEW.lc_freight_charge, '') || ' ' ||
    coalesce(NEW.lc_insurance_chg, '') || ' ' ||
    coalesce(NEW.lc_insurance_percentage, '') || ' ' ||
    coalesce(NEW.lc_insurance_amt, '') || ' ' ||
    coalesce(NEW.lc_invoice_num::text, '') || ' ' ||
    coalesce(NEW.lc_mawb_no, '') || ' ' ||
    coalesce(NEW.lc_mobl_no, '') || ' ' ||
    coalesce(NEW.lc_hawb_hobl_no, '') || ' ' ||
    coalesce(NEW.lc_marks_and_numbers, '') || ' ' ||
    coalesce(NEW.lc_no_of_pieces, '') || ' ' ||
    coalesce(NEW.lc_dimensions, '') || ' ' ||
    coalesce(NEW.lc_po_no, '') || ' ' ||
    coalesce(NEW.lc_city_state_of_origin, '') || ' ' ||
    coalesce(NEW.lc_country_of_origin, '') || ' ' ||
    coalesce(NEW.lc_1st_flight_number, '') || ' ' ||
    coalesce(NEW.lc_2nd_flight_number, '') || ' ' ||
    coalesce(NEW.lc_1st_to_city_code, '') || ' ' ||
    coalesce(NEW.lc_1st_to_city_code_value, '') || ' ' ||
    coalesce(NEW.lc_insurance_company_name, '') || ' ' ||
    coalesce(NEW.lc_insurance_company_address, '') || ' ' ||
    coalesce(NEW.lc_insurance_company_fax, '') || ' ' ||
    coalesce(NEW.lc_other_receipt_name, '') || ' ' ||
    coalesce(NEW.lc_other_receipt_address, '') || ' ' ||
    coalesce(NEW.lc_other_receipt_fax, '') || ' ' ||
    coalesce(NEW.lc_other_courier_name, '') || ' ' ||
    coalesce(NEW.lc_other_courier_add, '') || ' ' ||
    coalesce(NEW.lc_type, '') || ' ' ||
    coalesce(NEW.lc_amount_of_draw, '') || ' ' ||
    coalesce(NEW.lc_master_id::text, '') || ' ' ||
    coalesce(NEW.lc_secondapplicant_header, '') || ' ' ||
    coalesce(NEW.lc_secondapplicant_name, '') || ' ' ||
    coalesce(NEW.lc_secondapplicant_address, '')
);
    RETURN new;
end
$$ LANGUAGE plpgsql;


CREATE TRIGGER lc_tsvector_update_trigger
BEFORE INSERT OR UPDATE ON LC_INFO_TABLE
FOR EACH ROW
EXECUTE PROCEDURE lc_tsvector_update_function();